- name: Deploy Flask Application
  hosts: PyKubeDeploy
  become: true
  vars:
    app_directory: /app
    docker_image_name: pykubedeploy

  tasks:
   
    - name: Ensure application directory exists
      file:
        path: /app
        state: directory

    - name: Copy Dockerfile to the EC2 instance
      copy:
        src: Dockerfile
        dest: /app/Dockerfile

    - name: Copy requirements.txt to the EC2 instance
      copy:
        src: requirements.txt
        dest: /app/requirements.txt

    - name: Copy app.py to the EC2 instance
      copy:
        src: app.py
        dest: /app/app.py

    - name: Build the Docker image
      command: docker build -t pykubedeploy /app

    - name: Run the Docker container
      command: docker run -d -p 5000:5000 --name pykubedeploy pykubedeploy

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Copy docker-compose.yml file
      copy:
        src: docker-compose.yml
        dest: /app/docker-compose.yml

    - name: Run Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /app

