
- name: Deploy Flask Application
  hosts: PyKubeDeploy
  become: true
  vars:
    app_directory: /app
    docker_image_name: pykubedeploy

  tasks:
    - name: Install pip
      raw: python -m ensurepip --upgrade
      become: true
      become_user: root

    - name: Ensure application directory exists
      file:
        path: /app
        state: directory

    - name: Copy Dockerfile to the EC2 instance
      copy:
        src: Dockerfile
        dest: /app/Dockerfile

    - name: Copy requirements.txt to the EC2 instance
      copy:
       src: requirements.txt
       dest: /app/requirements.txt

    - name: Copy app.py to the EC2 instance
      copy:
        src: app.py
        dest: /app/app.py

    - name: Build the Docker image
      command: docker build -t pykubedeploy /app

    - name: Install dependencies inside the Docker container
      command: docker run -v /app pykubedeploy pip3 install --no-cache-dir -r /app/requirements.txt


    - name: Run the Docker container
      command: docker run -d -p 5000:5000 --name pykubedeploy pykubedeploy

