
- name: Deploy Flask Application
  hosts: PyKubeDeploy
  become: true
  vars:
    app_directory: /app
    docker_image_name: pykubedeploy

  tasks:
    - name: Ensure app directory exists
      file:
        path: /app
        state: directory
        mode: '0755'    

    - name: Copy project to the EC2 instance
      synchronize:
        src: ./
        dest: /app
        delete: yes
        recursive: yes

    - name: Build the Docker image
      shell: docker build -t pykubedeploy /app

    - name: Run the Docker container
      shell: docker run -d -p 5000:5000 --name pykubedeploy pykubedeploy

