- name: Deploy Flask Application
  hosts: PyKubeDeploy
  become: true
  vars:
    app_directory: /app
    docker_image_name: pykubedeploy

  tasks:
   
    - name: Ensure application directory exists
      file:
        path: /app
        state: directory

    - name: Copy Dockerfile to the EC2 instance
      copy:
        src: /app/Dockerfile
        dest: /app/Dockerfile

    - name: Copy requirements.txt to the EC2 instance
      copy:
        src: /app/requirements.txt
        dest: /app/requirements.txt

    - name: Copy app.py to the EC2 instance
      copy:
        src: /app/app.py
        dest: /app/app.py

    - name: Copy docker-compose.yml to the EC2 instance
      copy:
        src: /app/docker-compose.yml
        dest: /app/docker-compose.yml

    - name: Install Docker Compose
      become: yes
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Build and run the Docker Compose configuration
      shell: docker-compose up -d --build
      args:
        chdir: /app